name = "keyan-m/cardano-lottery"
version = "0.0.0"
compiler = "v1.1.3"
plutus = "v3"
license = "Apache-2.0"
description = "A decentralized and trust-less lottery contract on Cardano, leveraging the randomness of the proof-of-work token, Fortuna."

[repository]
user = "keyan-m"
project = "cardano-lottery"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "2.0.0"
source = "github"

[config]
